name: Draft Release

on:
  push:
    branches: [main]

permissions:
  actions: read
  contents: read

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_message.outputs.skip }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Check commit message
        id: check_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^bump\([0-9]+\.[0-9]+\.[0-9]+\): ]]; then
            echo "Commit message matches the ignore pattern."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Commit message: ${{ github.event.head_commit.message }}"
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Save to artifacts
        run: |
          echo "skip=${{ steps.check_message.outputs.skip }}" > message.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: check-commit-message
          path: message.txt
  detect-changes:
    if: needs.check-commit-message.outputs.skip != 'true'
    needs: check-commit-message
    name: Detect Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Get branch names
        uses: tj-actions/branch-names@v8
        id: branch-names

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Log branch
        run: |
          echo "is_default: ${{ steps.branch-names.outputs.is_default }}"
          if [ "${{ steps.branch-names.outputs.is_default }}" == "true" ]; then
            echo "Running on ${{ steps.branch-names.outputs.current_branch }}"
            echo "BASE SHA ${{ github.sha }}"
          else
            echo "Running on ${{ steps.branch-names.outputs.current_branch }} -> ${{ steps.branch-names.outputs.base_ref_branch }}"
            echo "HEAD SHA ${{ github.event.pull_request.head.sha }}"
            echo "BASE SHA ${{ github.event.pull_request.base.sha }}"
          fi

  lint-and-test:
    if: needs.check-commit-message.outputs.skip != 'true'
    needs: check-commit-message
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.10.0

      - name: Start NX CI
        run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Cache node_modules dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-

      - name: Install dependencies
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm i

      - name: NX SET SHAS
        uses: nrwl/nx-set-shas@v4

      - name: NX Affected
        run: pnpm exec nx affected -t lint stylelint test
  create-tag:
    if: needs.check-commit-message.outputs.skip != 'true'
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    name: Create Tag
    needs: [check-commit-message, detect-changes, lint-and-test]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          dry_run: true
          default_bump: patch
  delete-draft:
    needs: create-tag
    name: Delete Draft Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Get matching tags and delete draft releases
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ needs.create-tag.outputs.tag }}
        run: |
          # Fetch all tags that match the specified version
          matching_tags=$(gh release list --json tagName --jq '.[] | select(.tagName | startswith("'"$VERSION"'")) | .tagName')

          # Loop through each matching tag
          for tag in $matching_tags; do
            # Check if the release is a draft
            if gh release view $tag --json 'draft' | jq -e '.draft' > /dev/null; then
              echo "Deleting draft release with tag $tag..."
              gh release delete $tag -y
            fi
          done

  draft-release:
    needs: [create-tag, delete-draft]
    name: Draft Release
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Configure Git user
        run: |
          git config --global user.name "Aeiforge Administrator"
          git config --global user.email "administrator@aeiforge.com"
          git config --global user.username "aeiforge-administrator"
          git pull origin main

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Cache node_modules dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm i

      - name: Nx Report
        run: pnpm exec nx report

      - name: Create a GitHub release using NX
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: pnpm run release --version=${{ needs.create-tag.outputs.tag }}

      - name: Push to GitHub
        run: git push
